train:
  data_root: "/content/drive/MyDrive/AI_Project_LDR2HDR/data/train" # Adjust to your Drive folder
  ldr_dir: "LDR"
  hdr_dir: "HDR"
  batch_size: 4
  num_workers: 4 # Adjusted to suggested maximum for Colab
  epochs: 150
  learning_rate: 1e-4
  device: "cuda"
  save_interval: 10
  output_dir: "/content/drive/MyDrive/AI_Project_LDR2HDR/checkpoints"
