train:
  data_root: "/content/drive/MyDrive/LDR2HDR/data/train"  # change as needed
  ldr_dir: "LDR"          
  hdr_dir: "HDR"          
  batch_size: 4
  num_workers: 4
  epochs: 100
  learning_rate: 1e-4
  device: "cuda"         
  save_interval: 10      
  output_dir: "/content/drive/MyDrive/LDR2HDR/checkpoints"
