train:
  data_root: "/content/drive/MyDrive/ldr2hdr/data/train"  # Adjust to your Drive folder
  ldr_dir: "LDR"
  hdr_dir: "HDR"
  batch_size: 4
  num_workers: 2         # Adjusted to suggested maximum for Colab
  epochs: 100
  learning_rate: 1e-4
  device: "cuda"
  save_interval: 10
  output_dir: "/content/drive/MyDrive/ldr2hdr/checkpoints"
